apiVersion: v1
kind: Pod
metadata:
  name: app-trusted
  namespace: production
  labels:
    app: app-trusted
    role: trusted
spec:
  nodeSelector:
    node: Node3
  containers:
  - name: attacker
    image: postgres:15-alpine
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          echo "🚨 Attempting to connect to DB at $(date)" >&2;
          PGPASSWORD=demo123 psql -h postgres.production.svc.cluster.local -U demo -d demodb -c "SELECT now();" 2>&1;

          echo "🚨 Port scan (TCP connect) at $(date)" >&2;
          timeout 3 bash -c "</dev/tcp/postgres.production.svc.cluster.local/5432" 2>/dev/null && echo "✅ Port 5432 open" || echo "❌ Port 5432 closed"
          sleep 5;
        done
