apiVersion: v1
kind: Pod
metadata:
  name: external-tester
  namespace: external
  labels:
    app: external-tester
spec:
  containers:
  - name: tester
    image: postgres:15-alpine
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          echo "🚨 Attempting to connect to DB at $(date)" >&2;

          LOG_TIME=$(date)

          timeout 5s bash -c "
            PGPASSWORD=demodb psql -h postgres.production.svc.cluster.local -U app3 -d demodb \
            -c \"INSERT INTO access_log_3(source_pod, action) VALUES ('external-tester', 'Connected at ${LOG_TIME}');\"
          "

          if [ $? -eq 0 ]; then
            echo \"✅ INSERT log thành công vào DB\" >&2;
          else
            echo \"❌ INSERT log thất bại hoặc bị chặn bởi policy\" >&2;
          fi

          sleep 2;
        done