apiVersion: v1
kind: Pod
metadata:
  name: app-trusted
  namespace: production
  labels:
    app: app-trusted
    role: trusted
spec:
  nodeSelector:
    node: Node3
  containers:
  - name: trusted
    image: postgres:15-alpine
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          echo " [Attacker] Trying to connect to DB at $(date)" >&2;
          
          # Dùng timeout để kiểm soát lệnh không treo quá lâu
          timeout 5s bash -c 'PGPASSWORD=demo123 psql -h postgres.production.svc.cluster.local -U demo -d demodb -c "SELECT now();"'

          # Kiểm tra kết quả từ timeout
          if [ $? -eq 0 ]; then
            echo "✅ [TRUSTED] Connected to DB successfully at $(date)" >&2;
          else
            echo "❌ [TRUSTED] FAILED to connect to DB (timeout or error) at $(date)" >&2;
          fi

          sleep 10;
        done
