apiVersion: v1
kind: Pod
metadata:
  name: app-attacker
  namespace: production
  labels:
    app: attacker
spec:
  nodeSelector:
    node: Node3
  containers:
  - name: attacker
    image: postgres:15-alpine
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          echo "🚨 Attempting to connect to DB at $(date)" >&2;

          LOG_TIME=$(date)

          timeout 5s bash -c "
            PGPASSWORD=demodb psql -h postgres.production.svc.cluster.local -U app1 -d demodb \
            -c \"INSERT INTO access_log_1(source_pod, action) VALUES ('app-attacker', 'Connected at ${LOG_TIME}');\"
          "

          if [ $? -eq 0 ]; then
            echo \"✅ INSERT log thành công vào DB\" >&2;
          else
            echo \"❌ INSERT log thất bại hoặc bị chặn bởi policy\" >&2;
          fi

          sleep 10;
        done


