apiVersion: v1
kind: Pod
metadata:
  name: app-attacker
  labels:
    app: attacker
  namespace: networking-policy-demo
spec:
  containers:
  - name: attacker
    image: busybox
    command: ['sleep', '3600']