apiVersion: v1
kind: Pod
metadata:
  name: netshoot-node
  namespace: kube-system
spec:
  hostNetwork: true
  nodeSelector:
    node: Node2
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    securityContext:
      privileged: true
    command: ["sleep", "3600"]