apiVersion: v1
kind: Service
metadata:
  name: app-secure
  namespace: production
spec:
  selector:
    app: app-secure
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: app-secure
  namespace: production
  labels:
    app: app-secure
    role: trusted
spec:
  nodeSelector:
    node: Node2
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
