{
 "title": "Project Calico Monitoring Dashboard",
 "tags": [
  "attacker",
  "loki",
  "networkpolicy"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Số lượng pod được quản lý bởi calico node",
   "type": "gauge",
   "description": "Mỗi Pod trong Kubernetes được gán một interface (veth) bởi Calico. Interface này được gọi là endpoint trong Calico.\n\nMỗi endpoint tương ứng với một Pod.\n\nfelix_active_local_endpoints = 5 nghĩa là trên node này đang có 5 interface (của 5 pod) đang được Calico Felix quản lý.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "felix_active_local_endpoints{instance=~\".*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tổng số lượng policy hiện đang được Felix nhận từ datastore (etcd hoặc Kubernetes API)",
   "type": "gauge",
   "description": "Nếu mọi node đều hiển thị số giống nhau, tức là Calico Felix đã đồng bộ đúng toàn bộ policy trong cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "felix_cluster_num_policies{instance=~\".*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tổng route đang quản lý",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "felix_route_table_num_routes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Số policy đang áp dụng cục bộ",
   "type": "gauge",
   "description": " Số lượng network policy Calico đang hoạt động trên một node cụ thể.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "felix_active_local_policies{instance=~\".*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tổng số iptables rules được Felix cài đặt cho IPv4 trên node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 16, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(felix_iptables_rules{ip_version=\"4\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tổng lưu lượng WireGuard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(wireguard_bytes_rcvd[1m]))",
     "legendFormat": "Tổng lưu lượng nhận"
    },
    {
     "expr": "sum(rate(wireguard_bytes_sent[1m]))",
     "legendFormat": "Tổng lưu lượng gửi"
    }
   ]
  },
  {
   "title": "Trạng thái interface WireGuard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "wireguard_meta{iface=\"wireguard.cali\"}",
     "legendFormat": "{{iface}}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({app=\"db\"} |= \"INSERT INTO access_log_1\" [1m])",
     "legendFormat": "pod = app-attacker truy vấn"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({app=\"db\"} |= \"INSERT INTO access_log_2\" [1m])",
     "legendFormat": "pod = app-trusted truy vấn"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({app=\"db\"} |= \"INSERT INTO access_log_3\" [1m])",
     "legendFormat": "pod = external-tester truy vấn"
    }
   ]
  },
  {
   "title": "pod = app attacker truy cập đến database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({pod=\"app-attacker\"} |= \"log thành công vào DB\" [1m])",
     "legendFormat": "Số lượng truy vấn thành công"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({pod=\"app-attacker\"} |= \"log thất bại hoặc bị chặn bởi policy\" [1m])",
     "legendFormat": "Số lượng truy vấn không thành công"
    }
   ]
  },
  {
   "title": "pod = app-trusted có label là role = trusted -> pod database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({pod=\"app-trusted\"} |= \"INSERT log thành công vào DB\" [1m])",
     "legendFormat": "Số lượng truy vấn thành công"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({pod=\"app-trusted\"} |= \"INSERT log thất bại hoặc bị chặn bởi policy\" [1m])",
     "legendFormat": "Số lượng truy vấn không thành công"
    }
   ]
  },
  {
   "title": "pod = Externel test -> pod = Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({pod=\"external-tester\"} |= \"INSERT log thành công vào DB\"[1m])",
     "legendFormat": "Số lượng truy vấn thành công"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({pod=\"external-tester\"} |= \"INSERT log thất bại hoặc bị chặn bởi policy\"[1m])",
     "legendFormat": "Số lượng truy vấn thất bại"
    }
   ]
  }
 ]
}