apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: calico-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  namespaceSelector:
    matchNames:
      - kube-system
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s

