apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: monitoring
data:
  config.yaml: |
    receivers:
      filelog:
        include: [/var/log/containers/*.log] 
        start_at: beginning

      otlp:
        protocols:
          grpc:
          http:

      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              static_configs:
                - targets: ['localhost:8888']

    exporters:
      loki:
        endpoint: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

      prometheus:
        endpoint: "0.0.0.0:8889"

      debug: {}

    service:
      pipelines:
        logs:
          receivers: [filelog]
          exporters: [debug, loki]

        metrics:
          receivers: [otlp, prometheus]
          exporters: [prometheus, debug]
